### ISSUE TITLE
Confluent CLI and Java 11

### ISSUE THREAD

**Issue by gAmUssA** [confluentinc/confluent-cli#125]
As of 5.2 Confluent Platform supports Java 11.
https://docs.confluent.io/5.2.1/installation/versions-interoperability.html#java

Confluent CLI fails with

```
$ confluent start
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html

Current Java version '11' is unsupported at this time. Confluent CLI will exit.

WARNING: Java version 1.8 is recommended.
```

Kindly fix this check. Thank you

**Comment by gAmUssA** [comment]
Fixed in #126

**Comment by tianhao-au** [comment]
I still having the same error.
PS: Oracle JDK 11 and Confluent 5.2.1

**Comment by ybyzek** [comment]
This issue will be resolved in the next CP release.  In the interim, please edit the `$CONFLUENT_HOME/bin/confluent` file and comment out the java check
